### PR TITLE
Less use of reflection

### PR DESCRIPTION
**Pull request by osobolev**
The BasicHyperlinkUI class uses reflection on sun.* internal classes which generates warning on Java 11 and error on Java 17. This patch reduces the use of reflection and eliminates this possible warnings/errors.

### CODE REVIEW

**Comment by clausnagel** [comment]
Thanks for your contribution, @osobolev. Looks good to me. @yaozhihang, can you also have a look, please?

**Comment by yaozhihang** [comment]
Thanks @osobolev. The fix on the class `BasicHyperlinkUI.java` looks very good and should be adopted. The changes on other classes also make sence to get rid of Java reflection. But I think they are not in the scope of this pull request, and should be moved to a separate one.

**Comment by osobolev** [comment]
Thanks, I created new PR: #4

**Comment by clausnagel** [comment]
@osobolev, why have you closed this PR? The changes to `BasicHyperlinkUI.java` have been merged with #4, but are the changes to the other files from this PR not relevant anymore?

**Comment by osobolev** [comment]
Reopened it. Other changes are good to have too, they are just no so critical.

**Pull request merged**
